-- TransactionOS PostgreSQL schema
-- This mirrors the prototype transaction model for a managed PostgreSQL database.
CREATE TABLE IF NOT EXISTS users(user_id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL,created_at TEXT NOT NULL,expires_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(user_id));
CREATE TABLE IF NOT EXISTS properties(property_id TEXT PRIMARY KEY,address_line_1 TEXT NOT NULL,city TEXT,region TEXT,postal_code TEXT,country TEXT,latitude DOUBLE PRECISION,longitude DOUBLE PRECISION,property_type TEXT,jurisdiction TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS property_parties(party_id TEXT PRIMARY KEY,property_id TEXT NOT NULL,user_id TEXT,role TEXT NOT NULL,name TEXT NOT NULL,email TEXT,authority_status TEXT DEFAULT 'PENDING',FOREIGN KEY(property_id) REFERENCES properties(property_id),FOREIGN KEY(user_id) REFERENCES users(user_id));
CREATE TABLE IF NOT EXISTS transactions(transaction_id TEXT PRIMARY KEY,property_id TEXT NOT NULL,status TEXT NOT NULL,created_by TEXT,created_at TEXT NOT NULL,FOREIGN KEY(property_id) REFERENCES properties(property_id));
CREATE TABLE IF NOT EXISTS offers(offer_id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL,status TEXT NOT NULL,current_version_id TEXT,current_version_number INTEGER DEFAULT 0,created_by TEXT,created_at TEXT NOT NULL,FOREIGN KEY(transaction_id) REFERENCES transactions(transaction_id));
CREATE TABLE IF NOT EXISTS offer_versions(version_id TEXT PRIMARY KEY,offer_id TEXT NOT NULL,version_number INTEGER NOT NULL,actor_party_id TEXT,status TEXT NOT NULL,payload_json TEXT NOT NULL,submitted_at TEXT,accepted_at TEXT,deadline_at TEXT,FOREIGN KEY(offer_id) REFERENCES offers(offer_id));
CREATE TABLE IF NOT EXISTS conditions(condition_id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL,label TEXT NOT NULL,owner TEXT,status TEXT NOT NULL,due_at TEXT,FOREIGN KEY(transaction_id) REFERENCES transactions(transaction_id));
CREATE TABLE IF NOT EXISTS documents(document_id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL,name TEXT NOT NULL,status TEXT NOT NULL,storage_ref TEXT,FOREIGN KEY(transaction_id) REFERENCES transactions(transaction_id));
CREATE TABLE IF NOT EXISTS signatures(signature_id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL,document_id TEXT,party_id TEXT,status TEXT NOT NULL,signed_at TEXT,evidence_json TEXT,FOREIGN KEY(transaction_id) REFERENCES transactions(transaction_id));
CREATE TABLE IF NOT EXISTS events(event_id TEXT PRIMARY KEY,transaction_id TEXT,type TEXT NOT NULL,actor_party_id TEXT,occurred_at TEXT NOT NULL,metadata_json TEXT);
CREATE TABLE IF NOT EXISTS deposits(deposit_id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL,required_amount_cents INTEGER NOT NULL,status TEXT NOT NULL,provider_ref TEXT,received_at TEXT,held_at TEXT,released_at TEXT,refunded_at TEXT,dispute_reason TEXT,created_at TEXT NOT NULL,FOREIGN KEY(transaction_id) REFERENCES transactions(transaction_id));
CREATE TABLE IF NOT EXISTS transaction_tasks(task_id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL,label TEXT NOT NULL,owner TEXT NOT NULL,status TEXT NOT NULL,due_at TEXT,sequence INTEGER NOT NULL,metadata_json TEXT,created_at TEXT NOT NULL,completed_at TEXT,FOREIGN KEY(transaction_id) REFERENCES transactions(transaction_id));
CREATE TABLE IF NOT EXISTS identity_verifications(verification_id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL,user_id TEXT NOT NULL,legal_name TEXT NOT NULL,email TEXT,status TEXT NOT NULL,method TEXT NOT NULL,verified_at TEXT,created_at TEXT NOT NULL,FOREIGN KEY(transaction_id) REFERENCES transactions(transaction_id),FOREIGN KEY(user_id) REFERENCES users(user_id));
CREATE TABLE IF NOT EXISTS transaction_communications(communication_id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL,channel TEXT NOT NULL,sender TEXT,recipient TEXT,message TEXT NOT NULL,status TEXT NOT NULL,related_type TEXT,related_id TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS transaction_risks(risk_id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL,severity TEXT NOT NULL,category TEXT NOT NULL,title TEXT NOT NULL,detail TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,resolved_at TEXT);
CREATE TABLE IF NOT EXISTS transaction_controls(transaction_id TEXT PRIMARY KEY,paused INTEGER NOT NULL DEFAULT 0,pause_reason TEXT,updated_at TEXT NOT NULL,FOREIGN KEY(transaction_id) REFERENCES transactions(transaction_id));
CREATE TABLE IF NOT EXISTS brain_evaluations(evaluation_id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL,state TEXT NOT NULL,priority TEXT NOT NULL,next_action_json TEXT,automated_json TEXT,escalations_json TEXT,reason TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(transaction_id) REFERENCES transactions(transaction_id));
